### ISSUE TITLE
feedback from Anton's class

### ISSUE THREAD

**Issue by martenson** [galaxyproject/planemo-machine#54]
Today I have been to @nekrut 's class where he used planemo-machine to teach students how to wrap tools for Galaxy. Some notes:
- Reorder the appliance list. Ova first? That is the best choice for a beginner.
- Note in docs about how clipboard works
- Set up bigger terminal font
- Upgrade planemo in the appliance
- Do you have to restart galaxy to see the tool? Hot load?

**Comment by jmchilton** [comment]
Moving these issues into https://github.com/galaxyproject/planemo-machine/issues/43 - since they feel similar in nature - general polish ideas discovered during running tutorials.

> Do you have to restart galaxy to see the tool? Hot load?

This is a bug they should definitely just show up. Did they never show up?

> Reorder the appliance list. Ova first? That is the best choice for a beginner.

I think I agree with this - Docker feels more future facing but that may be a ways off.

> Upgrade planemo in the appliance

Here - I think we need continuous testing, integration, and deployment on new images. I'm working on this but it is going slowly.

**Comment by martenson** [comment]
ha, I vaguely remembered and was looking for that issue, but did not find it :) thanks @jmchilton
